name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: sudo apt-get install libxml2-dev libxslt-dev
      - run: pip install black codespell flake8 isort pytest pyupgrade wheel
      - run: black --check . || true
      - run: codespell --ignore-words-list="noone" --quiet-level=2  # --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: isort --profile black . || true
      - run: pip install -r requirements.txt || true
      - run: pytest .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
